name: Run Unit Tests
on: [push, pull_request]

defaults:
  run:
    working-directory: src

jobs:
  build:
    name: Build, lint, and test on Python ${{ matrix.python-version}} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ["3.8", "3.9"]
        os: [ubuntu-latest]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Use Node ${{ matrix.python-version}}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version}}
      - name: Install app dependencies
        run: |
            python -m pip install --upgrade pip
            pip install pipenv 
            pipenv install --dev 
      - name: Test application units
        run: $FURY_TOKEN pipenv run pytest -v 
        env: 
            FURY_TOKEN: ${{ secrets.FURY_TOKEN }}
